"""initial schema

Revision ID: 04b90ff0aba0
Revises: 
Create Date: 2026-09-03 18:41:48.300788
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '04b90ff0aba0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('ua_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anon_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anon_sessions_ip_hash'), ['ip_hash'], unique=False)

    op.create_table('fingerprints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('detection_method', sa.Text(), nullable=False),
    sa.Column('target_content', sa.String(length=24), nullable=False),
    sa.Column('coverage', sa.String(length=255), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_token_hash'), ['token_hash'], unique=True)

    op.create_table('quota_windows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_type', sa.String(length=8), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', name='uq_quota_owner')
    )
    with op.batch_alter_table('quota_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quota_windows_owner_id'), ['owner_id'], unique=False)

    op.create_table('scan_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_type', sa.String(length=8), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_events_owner_id'), ['owner_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('signal_level', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_oauth_provider_account')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_exchange_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_exchange_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_exchange_codes_code_hash'), ['code_hash'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('oauth_exchange_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_exchange_codes_code_hash'))

    op.drop_table('oauth_exchange_codes')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))

    op.drop_table('analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_api_key'))

    op.drop_table('users')
    with op.batch_alter_table('scan_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_scan_events_created_at'))

    op.drop_table('scan_events')
    with op.batch_alter_table('quota_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quota_windows_owner_id'))

    op.drop_table('quota_windows')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_token_hash'))
        batch_op.drop_index(batch_op.f('ix_magic_links_email'))

    op.drop_table('magic_links')
    op.drop_table('fingerprints')
    with op.batch_alter_table('anon_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anon_sessions_ip_hash'))

    op.drop_table('anon_sessions')
    # ### end Alembic commands ###
