"""add ai verdict to analyses

Revision ID: 38ac89a5253a
Revises: 04b90ff0aba0
Create Date: 2026-09-03 19:27:51.004604
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '38ac89a5253a'
down_revision: str | None = '04b90ff0aba0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'analyses',
        sa.Column('ai_verdict', sa.String(length=24), nullable=False, server_default='no_evidence'),
    )
    op.add_column(
        'analyses',
        sa.Column('ai_probability', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'ai_probability')
    op.drop_column('analyses', 'ai_verdict')
    # ### end Alembic commands ###
