"""Curated catalogue of real-world provenance / watermarking detection methods.

Sources are linked per entry. Descriptions are deliberately conservative: this
tool inspects for *known signals*, it does not claim to prove authorship.
"""

FINGERPRINTS: list[dict] = [
    {
        "id": "c2pa-content-credentials",
        "name": "C2PA Content Credentials",
        "provider": "C2PA / Content Authenticity Initiative",
        "type": "cryptographic",
        "version": "2.1",
        "status": "available",
        "confidence": 98,
        "target_content": "image",
        "coverage": "JPEG, PNG, WebP, AVIF, MP4, PDF, WAV",
        "detection_method": (
            "Parse the embedded C2PA manifest store, verify the COSE signature "
            "chain against known trust lists and check assertion hashes against "
            "the asset."
        ),
        "description": (
            "An open standard for cryptographically signed content provenance. A "
            "valid manifest states who produced or edited an asset and how, "
            "including whether generative AI tools were used. Absence of a "
            "manifest is not evidence of anything; a present manifest can still "
            "be from an untrusted signer."
        ),
        "last_updated": "2026-06-30",
        "references": ["https://c2pa.org/specifications/"],
        "sort_order": 1,
    },
    {
        "id": "synthid-text",
        "name": "SynthID Text",
        "provider": "Google DeepMind",
        "type": "statistical",
        "version": "1.x",
        "status": "research",
        "confidence": 80,
        "target_content": "text",
        "coverage": "English and several other languages, model-dependent",
        "detection_method": (
            "Tournament sampling watermark: generation biases token choices via a "
            "pseudo-random g-function keyed on context. Detection scores the "
            "mean g-value of observed tokens against the null distribution."
        ),
        "description": (
            "A generative text watermark that perturbs token sampling so a "
            "detector holding the key can estimate whether text came from a "
            "watermarked model. Robustness drops with heavy editing, "
            "paraphrasing or short samples. Only the key holder can verify."
        ),
        "last_updated": "2026-05-14",
        "references": ["https://www.nature.com/articles/s41586-024-08025-4"],
        "sort_order": 2,
    },
    {
        "id": "synthid-image",
        "name": "SynthID (image / audio / video)",
        "provider": "Google DeepMind",
        "type": "statistical",
        "version": "n/a",
        "status": "research",
        "confidence": 75,
        "target_content": "image",
        "coverage": "Outputs of Google generative models (Imagen, Lyria, Veo)",
        "detection_method": (
            "An imperceptible pixel/spectrogram-domain watermark embedded at "
            "generation time; a trained detector reports a confidence band."
        ),
        "description": (
            "A proprietary invisible watermark applied to media generated by "
            "Google's models. Third parties cannot verify it without Google's "
            "detector; this tool only records that the signal class exists."
        ),
        "last_updated": "2026-05-14",
        "references": ["https://deepmind.google/technologies/synthid/"],
        "sort_order": 3,
    },
    {
        "id": "iptc-digital-source-type",
        "name": "IPTC Digital Source Type",
        "provider": "IPTC",
        "type": "structural",
        "version": "2023.1",
        "status": "available",
        "confidence": 90,
        "target_content": "image",
        "coverage": "Any file carrying IPTC Photo Metadata (XMP)",
        "detection_method": (
            "Read the XMP property Iptc4xmpExt:DigitalSourceType and flag values "
            "such as trainedAlgorithmicMedia or compositeWithTrainedAlgorithmicMedia."
        ),
        "description": (
            "A controlled vocabulary many platforms and cameras write into image "
            "metadata to declare how a picture was produced, including AI "
            "generation. Trivial to strip or forge, so treat as a hint."
        ),
        "last_updated": "2026-02-01",
        "references": ["https://cv.iptc.org/newscodes/digitalsourcetype/"],
        "sort_order": 4,
    },
    {
        "id": "unicode-invisible-characters",
        "name": "Invisible Unicode markers",
        "provider": "Generic",
        "type": "structural",
        "version": "1.0",
        "status": "available",
        "confidence": 95,
        "target_content": "text",
        "coverage": "All Unicode text",
        "detection_method": (
            "Scan for zero-width characters (U+200B to U+200D, U+2060, U+FEFF), "
            "Unicode Tags block (U+E0000 to U+E007F), bidi controls and unusual "
            "variation selectors; report counts and positions."
        ),
        "description": (
            "Zero-width and tag characters can encode hidden data or act as a "
            "crude watermark. They also occur naturally (e.g. emoji sequences, "
            "ligature control), so context matters."
        ),
        "last_updated": "2026-07-20",
        "references": ["https://www.unicode.org/faq/unsup_char.html"],
        "sort_order": 5,
    },
    {
        "id": "homoglyph-substitution",
        "name": "Homoglyph substitution",
        "provider": "Generic",
        "type": "structural",
        "version": "1.0",
        "status": "available",
        "confidence": 88,
        "target_content": "text",
        "coverage": "Latin / Cyrillic / Greek confusable sets",
        "detection_method": (
            "Compare each letter against the Unicode confusables table; flag "
            "runs where a Latin word contains Cyrillic or Greek look-alikes."
        ),
        "description": (
            "Swapping visually identical characters between scripts can smuggle "
            "signals through copy-paste or defeat naive string matching. Common "
            "in phishing; occasionally used as a fragile watermark."
        ),
        "last_updated": "2026-07-20",
        "references": ["https://www.unicode.org/Public/security/latest/confusables.txt"],
        "sort_order": 6,
    },
    {
        "id": "kgw-green-list-watermark",
        "name": "Green-list token watermark (KGW)",
        "provider": "Kirchenbauer et al. (academic)",
        "type": "statistical",
        "version": "2023",
        "status": "research",
        "confidence": 70,
        "target_content": "text",
        "coverage": "English; any model the scheme is applied to",
        "detection_method": (
            "A hash of the previous token seeds a pseudo-random split of the "
            "vocabulary into green/red lists; generation favours green tokens. A "
            "one-proportion z-test on the green-token rate yields a p-value."
        ),
        "description": (
            "The reference open watermarking scheme for LLM text. Detection "
            "needs the hashing scheme and key; paraphrase attacks and low "
            "entropy passages weaken it substantially."
        ),
        "last_updated": "2026-01-10",
        "references": ["https://arxiv.org/abs/2301.10226"],
        "sort_order": 7,
    },
    {
        "id": "ngram-frequency-deviation",
        "name": "N-gram frequency deviation",
        "provider": "Independent",
        "type": "statistical",
        "version": "0.4",
        "status": "experimental",
        "confidence": 55,
        "target_content": "text",
        "coverage": "English, French, German reference tables",
        "detection_method": (
            "Chi-square comparison of observed character and word n-gram "
            "frequencies against a language reference corpus; also reports "
            "Shannon entropy and type-token ratio."
        ),
        "description": (
            "A scheme-agnostic statistical probe. Large deviations can indicate "
            "templated text, translation artefacts or watermarking, but never "
            "identify a source on their own."
        ),
        "last_updated": "2026-08-01",
        "references": [],
        "sort_order": 8,
    },
    {
        "id": "exif-software-tags",
        "name": "EXIF / XMP software & AI tags",
        "provider": "Generic",
        "type": "structural",
        "version": "1.0",
        "status": "available",
        "confidence": 85,
        "target_content": "image",
        "coverage": "JPEG, PNG, TIFF, WebP, HEIC",
        "detection_method": (
            "Read EXIF (Software, ProcessingSoftware), XMP (CreatorTool, "
            "xmpMM history) and PNG text chunks; match against known generator "
            "signatures (e.g. 'Stable Diffusion', 'Midjourney', 'DALL·E')."
        ),
        "description": (
            "Editing and generation tools often leave their name in metadata. "
            "Useful corroboration, but metadata is routinely removed by social "
            "platforms and easily edited."
        ),
        "last_updated": "2026-06-15",
        "references": ["https://exiftool.org/TagNames/"],
        "sort_order": 9,
    },
    {
        "id": "openai-c2pa",
        "name": "OpenAI Content Credentials",
        "provider": "OpenAI",
        "type": "cryptographic",
        "version": "C2PA 1.3",
        "status": "available",
        "confidence": 95,
        "target_content": "image",
        "coverage": "DALL·E 3 and ChatGPT image outputs",
        "detection_method": (
            "Verify a C2PA manifest signed by OpenAI's certificate and check "
            "the c2pa.actions assertion for 'created' with a generative "
            "digitalSourceType."
        ),
        "description": (
            "OpenAI attaches signed Content Credentials to images from its "
            "image models. Removed if the file is re-encoded without preserving "
            "metadata."
        ),
        "last_updated": "2026-03-01",
        "references": ["https://help.openai.com/en/articles/8912793"],
        "sort_order": 10,
    },
    {
        "id": "adobe-firefly-credentials",
        "name": "Adobe Firefly Content Credentials",
        "provider": "Adobe",
        "type": "cryptographic",
        "version": "C2PA 1.3",
        "status": "available",
        "confidence": 95,
        "target_content": "image",
        "coverage": "Adobe Firefly, Photoshop generative features",
        "detection_method": (
            "Verify the C2PA manifest against Adobe's trust list; inspect "
            "ingredient assertions for generative steps."
        ),
        "description": (
            "Adobe embeds Content Credentials by default in Firefly output and "
            "optionally in Creative Cloud exports. Can also be looked up on "
            "Adobe's Verify service if stripped."
        ),
        "last_updated": "2026-04-12",
        "references": ["https://helpx.adobe.com/creative-cloud/help/content-credentials.html"],
        "sort_order": 11,
    },
    {
        "id": "legacy-lsb-steganography",
        "name": "LSB steganography (legacy)",
        "provider": "Generic",
        "type": "pattern",
        "version": "n/a",
        "status": "deprecated",
        "confidence": 40,
        "target_content": "image",
        "coverage": "Lossless bitmaps (PNG, BMP)",
        "detection_method": (
            "Chi-square and sample-pair analysis of least-significant-bit "
            "planes to detect non-natural bit distributions."
        ),
        "description": (
            "Hiding payloads in the low bits of pixel values. Easily destroyed "
            "by recompression and rarely used for modern provenance signalling; "
            "kept for completeness."
        ),
        "last_updated": "2025-11-02",
        "references": [],
        "sort_order": 20,
    },
]
